--- !ruby/object:VR_ENV
browser: firefox
width: 1141
height: 657
panel_pos: 360
backup_path: C:/Users/HP BE
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- C:/Users/HP BE/Desktop/Application_Ruby/bin/MyClass.rb
open_folders:
- C:/Users/HP BE/Desktop/Application_Ruby
- C:/Users/HP BE/Desktop/Application_Ruby/bin
- C:/Users/HP BE/Desktop/Application_Ruby/bin/glade
current_file: C:/Users/HP BE/Desktop/Application_Ruby/bin/MyClass.rb
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
