--- !ruby/object:VR_ENV
browser: firefox
width: 800
height: 722
panel_pos: 503
backup_path: C:/Users/HP BE
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- C:/Users/HP BE/Desktop/Adin/Reddit/bin/TwitterLoginWindow.rb
- C:/Users/HP BE/Desktop/Adin/Reddit/bin/RedditWindowGUI.rb
- C:/Users/HP BE/Desktop/Adin/Reddit/main.rb
- C:/Users/HP BE/Desktop/Adin/Reddit/bin/RedditLoginWindow.rb
open_folders:
- C:/Users/HP BE/Desktop/Adin/Reddit
- C:/Users/HP BE/Desktop/Adin/Reddit/bin
- C:/Users/HP BE/Desktop/Adin/Reddit/bin/glade
current_file: C:/Users/HP BE/Desktop/Adin/Reddit/bin/RedditLoginWindow.rb
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
